{% set name = "deepdiff" %}
{% set version = "8.0.0" %}
{% set sha256 = "1f751f39984a0516686fddeccb80d43903abd14ac42d2ebeb8ae7c4f91420c6d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - orderly-set ==5.2.1
    - python >=3.8

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - deepdiff

about:
  home: https://github.com/seperman/deepdiff
  summary: Deep Difference and Search of any Python object/data.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    Deep Difference of dictionaries, iterables, strings and other objects. 
    It will recursively look for all the changes.
  doc_url: http://deepdiff.readthedocs.io/en/latest/
  dev_url: https://github.com/seperman/deepdiff

extra:
  recipe-maintainers:
    - loriab
    - seperman
    - synapticarbors
