{% set name = "deepdiff" %}
{% set version = "4.0.2" %}
{% set sha256 = "f263bf42d3b4eaac8359100f59497e98ae40ea256402b9c75e8c20add9fdbdb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jsonpickle

test:
  imports:
    - deepdiff

about:
  home: https://github.com/seperman/deepdiff
  summary: 'Deep Difference and Search of any Python object/data.'
  license: MIT
  license_family: MIT
  description: |
    Deep Difference of dictionaries, iterables, strings and other
    objects. It will recursively look for all the changes. Tested on
    Python 2.7, 3.3, 3.4, 3.5, 3.6, Pypy, Pypy3
  doc_url: http://deepdiff.readthedocs.io/en/latest/
  dev_url: https://github.com/seperman/deepdiff

extra:
  recipe-maintainers:
    - loriab
    - seperman
